# config.toml

[general]
total_requests = 500  # Tedade kolle paket-haei ke ferestandeh mifreste
port = 12345          # Porti ke test rush anjam mishe

[sender]
ip = "216.26.131.92"   # IP vagheyi Sender

[receiver]
ip = "104.209.123.240"   # IP vagheyi Receiver

[target]

# Mitoni ye range network bedi (mesle 10.0.0.0/24) ya ye IP tak (mesle 10.0.0.5)
test_ips = "1.1.1.0/24"
